name: ESP-BOX Factory Demo Build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Install ESP-IDF
        run: |
          mkdir -p /opt/esp
          cd /opt/esp
          git clone --recursive https://github.com/espressif/esp-idf.git
          cd esp-idf
          git checkout v5.0.4
          ./install.sh esp32s3

      - name: Build firmware
        run: |
          git config --global --add safe.directory $GITHUB_WORKSPACE
          . /opt/esp/esp-idf/export.sh
          cd examples/factory_demo
          idf.py set-target esp32s3
          idf.py build
