name: ESP-BOX HUB CI

on:
  push:
  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-latest

    container:
      image: espressif/idf:release-v5.1

    steps:

      - name: Checkout repository
        uses: actions/checkout@v4


      - name: Fix Git safe directory
        run: git config --global --add safe.directory $GITHUB_WORKSPACE


      - name: Create clean firmware workspace
        shell: bash
        run: |
          mkdir firmware
          cd firmware

          mkdir main

          cat << 'EOF' > CMakeLists.txt
          cmake_minimum_required(VERSION 3.16)
          include($ENV{IDF_PATH}/tools/cmake/project.cmake)
          project(esp_box_hub)
          EOF


          cat << 'EOF' > main/main.c
          #include "freertos/FreeRTOS.h"
          #include "freertos/task.h"
          #include "esp_log.h"

          static const char *TAG = "ESP_BOX";

          void app_main(void)
          {
              ESP_LOGI(TAG, "ESP BOX HUB STARTED");

              while (1)
              {
                  ESP_LOGI(TAG, "Hub running...");
                  vTaskDelay(pdMS_TO_TICKS(5000));
              }
          }
          EOF


          cat << 'EOF' > main/CMakeLists.txt
          idf_component_register(
              SRCS "main.c"
              INCLUDE_DIRS "."
          )
          EOF


      - name: Build firmware
        shell: bash
        run: |
          . $IDF_PATH/export.sh
          cd firmware
          idf.py set-target esp32s3
          idf.py build


      - name: Upload firmware
        uses: actions/upload-artifact@v4
        with:
          name: espbox-firmware
          path: |
            firmware/build/*.bin
            firmware/build/*.elf
