name: ESP-BOX HUB CI

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: espressif/idf:release-v5.1

    steps:
      - uses: actions/checkout@v4

      - run: git config --global --add safe.directory $GITHUB_WORKSPACE

      # 🔥 STEP 1: Load components + models
      - name: Prepare ESP-SR
        run: |
          cd examples/esp-box/firmware
          . $IDF_PATH/export.sh
          idf.py reconfigure

      # 🔥 STEP 2: Copy model locally
      - name: Copy model
        run: |
          cd examples/esp-box/firmware
          mkdir -p main/model
          cp -r managed_components/espressif__esp-sr/model/* main/model/

      # 🔥 STEP 3: Build
      - name: Build firmware
        run: |
          cd examples/esp-box/firmware
          . $IDF_PATH/export.sh
          idf.py set-target esp32s3
          idf.py fullclean
          idf.py build

      # 🔥 STEP 4: Upload
      - uses: actions/upload-artifact@v4
        with:
          name: espbox-firmware
          path: |
            examples/esp-box/firmware/build/*.bin
            examples/esp-box/firmware/build/bootloader/*.bin
            examples/esp-box/firmware/build/partition_table/*.bin
