name: FactoryDemo

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: espressif/idf:release-v5.1

    steps:
      - name: Checkout ESP-BOX
        uses: actions/checkout@v4
        with:
          repository: espressif/esp-box
          submodules: recursive

      - name: Fix Git Safe Directory
        run: git config --global --add safe.directory '*'

      - name: Build Factory Demo (ESP-IDF native)
        run: |
          set -e
          . $IDF_PATH/export.sh

          cd examples/factory_demo

          idf.py set-target esp32s3
          cp sdkconfig.ci.box sdkconfig

          idf.py fullclean build

      - name: Show build output
        run: |
          cd examples/factory_demo/build
          ls -lh

      - name: Upload firmware binaries
        uses: actions/upload-artifact@v4
        with:
          name: factory-demo
          path: |
            examples/factory_demo/build/*.bin
