name: Build ESP-BOX OS

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Run build script
      run: |
        chmod +x tools/build_espbox_os.sh
        ./tools/build_espbox_os.sh
    
    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: patches
        path: patches/
